services:
  registry:
    image: ghcr.io/fluoritejs/registry:v0.1.0
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - registry-data:/app/data
      - ./deployment.yaml:/app/deployment.yaml:ro
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped

volumes:
  registry-data:
